name: traffic-counter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Tests
      run: sbt clean test
    - name: Run Package
      run: sbt assembly
    - run: |
        echo "test Jar file"
        java -jar target/scala-2.13/trafficcounter.jar src/main/resources/data/

